### ISSUE TITLE
Sobre el montaje de un ambiente de desarrollo

### ISSUE THREAD

**Issue by lesthack** [djangomx/djangomx#16]
Acabo de clonarme el proyecto y he tratado de levantarlo en la rama development. Sin embargo me encontré con varios detalles.

1. Parece que no basta con hacer 'git submodule update --init' (aunque en la rama master si está)
    Tuve que agregar el modulo manual en el path djangomx.
    $ cd djangomx
    $ git submodule add https://github.com/netoxico/utilities.git

2. Dentro de los requeriments, parece faltar django_extensions.
    $ pip install django_extensions

3. Dado que el proyecto usa django-compressor, es necesario instalar less.
    $ npm install -g less

Espero esto pueda ayudar a los que quiere colaborar.

**Comment by andyosuna** [comment]
Hola, quité el submódulo y lo pasé al app de `core`. El readme está bastante mas amigable ahora: https://github.com/djangomx/djangomx/tree/development 
Si tienes alguna sugerencia envía tu PR :dizzy:
